[package]
name = "todotxt-to-json"
version = "0.1.0"
authors = ["Zachary Golba <zachary.golba@postlight.com>"]

[dependencies]
serde_json = "1.0.17"
failure = "0.1.1"

[dependencies.todotxt]
features = ["serde"]
path = "../../todotxt"
