[package]
name = "to2txt-repl"
version = "0.1.0"
authors = ["Zachary Golba <zachary.golba@postlight.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1"
wasm-bindgen = "0.2"

[dependencies.to2txt]
path = "../../../to2txt"
features = ["serde"]
