name: repl

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install
        run: npm ci
        working-directory: ./examples/to2txt-repl

      - name: Lint
        run: pnpm lint
        working-directory: ./examples/to2txt-repl

      - name: Format
        run: pnpm fmt
        working-directory: ./examples/to2txt-repl

      - name: Build Rust
        run: |
          rustup component add clippy rustfmt
          rustc --version
        working-directory: ./examples/to2txt-repl

      - name: Test
        run: pnpm test
        working-directory: ./examples/to2txt-repl
