name: to2txt

on:
  pull_request:
  push:
    branches:
      - main

env:
  RUSTFLAGS: -Dwarnings

jobs:
  fmt-clippy-and-docs:
    name: fmt, clippy, and docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Rust
        run: |
          rustup component add clippy rustfmt
          rustc --version

      - name: Clippy
        run: cargo clippy --tests --examples -- -D warnings

      - name: Rustfmt
        run: cargo fmt --all -- --check

      - name: Docs
        run: cargo doc --no-deps

  test:
    name: build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]

    steps:
      - uses: actions/checkout@v4

      - name: Configure Rust
        run: |
          rustup install ${{ matrix.rust }}
          rustup default ${{ matrix.rust }}
          rustup component add clippy rustfmt
          rustc --version

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test
